version: "3.9"

services:

  backend:
    build: ./backend
    container_name: innovatex-backend
    ports:
      - "8000:8000"
    volumes:
      # Let annotated images persist and be accessible
      - ./backend/static:/app/static
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: innovatex-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
